### ISSUE TITLE
Makefile and less dependencies?

### ISSUE THREAD

**Issue by open-educational-resources** [Israel-D/homeschool-mathtimer#1]
Hello,

The programme is awesome !!!

cmake is comfortable for programmers and developers. However it could be interesting to avoid using cmake and to clean up the dependencies. Would it be possible to reduce the content in order to make it more accessible to compilation?

Thank you !

**Comment by Israel-D** [comment]
@open-educational-resources I have a PPA with all my homeschooling games in it.
https://code.launchpad.net/~israeldahl/+archive/ubuntu/homeschool
You could (possibly) just extract the binary + static library with the appropriate libraries installed and it may work, also I could make an AppImage for it, fairly easily.

The reason for some of the dependencies is that cmake is a bit quirky with varying GNU/Linux systems (Arch and Debian/Ubuntu and Fedora do not agree on the FLTK dependencies in cmake).  The others are some FLTK dependencies for X11 specific things (like creating window icons).  I am not sure if it would work on BSD (not sure if FLTK has been ported there)

The other reason is that I reused some code I already have.  I am sure that if you wanted you could just move the functions from common and fltkfunctions into the main program and limit the dependencies in that way as well (probably some of the X depends are not used).

If you want to go ahead and tweak the code and remove cmake then please do.  I have been really busy lately so I do not currently have the time to do this.

**Comment by open-educational-resources** [comment]
You have excellent skills in programming, I wonder why cmake and some dependencies which make compilation tenious. FLTK runs well on NetBSD and it is possible to make the code compilable on Unix systems. I would like to, but I have currently more dev on termcap library. Due to portability of terminal applications on any operating systems.

**Comment by Israel-D** [comment]
Ok this should fix it now.
I updated the README (at the bottom)
just
 ```
cd src
fltk-config --use-images --compile math-timer.cxx
```

**Comment by Israel-D** [comment]
@open-educational-resources I also recently added a bunch of my other stuff to github and make the build process similar they are all my homeschool-* repos  If you find any don't build please let me know, as I did it rather quickly and might have missed something on one of them

**Comment by Israel-D** [comment]
@open-educational-resources I just wanted to let you know I made my programs all use a standard 
`./configure && make` procedure
I also made most of them even smaller
